### ISSUE TITLE
Colima fails to start

### ISSUE THREAD

**Issue by armenzg** [getsentry/bootstrap-sentry#50]
I've been setting up a new laptop and I got Colima to fail for me. This is an M2

CC @joshuarli 

```
armenzg@MacBook-Air ~ % bash <(curl -s https://raw.githubusercontent.com/getsentry/bootstrap-sentry/main/bootstrap.sh)
--> Enter your password (for sudo access):
--> Enter absolute path where we'll clone source code [/Users/armenzg/code]: 
--> Installing sentry-cli
OK
--> Checking GitHub access
OK
--> Installing Homebrew: OK
--> Updating Homebrew: ==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:905b0c3896164ae8067a22fff2fd0b80b16d3c8bb72441403eedf69da71ec717
############################################################################################################################################################################### 100.0%
==> Pouring portable-ruby-2.6.10_1.arm64_big_sur.bottle.tar.gz
OK
grep: /Users/armenzg/.zprofile: No such file or directory
--> Installing Homebrew taps and extensions:
Tapping homebrew/cask
Tapping homebrew/core
Tapping homebrew/services
Homebrew Bundle complete! 3 Brewfile dependencies now installed.
OK
--> Cloning getsentry/getsentry to /Users/armenzg/code/getsentry
OK
--> Installing from sentry Brewfile (very slow)
Installing colima
Installing docker
Installing docker-buildx
Installing pyenv
Installing openssl
Installing readline
Installing watchman
Using homebrew/cask
Installing chromedriver
Homebrew Bundle complete! 9 Brewfile dependencies now installed.
OK
--> Install python via pyenv python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.8.16.tar.xz...
-> https://www.python.org/ftp/python/3.8.16/Python-3.8.16.tar.xz
Installing Python-3.8.16...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.8.16 to /Users/armenzg/.pyenv/versions/3.8.16
Adding pyenv init --path to /Users/armenzg/.zprofile...
--> Tail of /Users/armenzg/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"
# It is assumed that pyenv is installed via Brew, so this is all we need to do. 
eval "$(pyenv init --path)"
OK
--> Creating virtualenv in /Users/armenzg/code/sentry
OK
--> Installing sentry env vars to startup script... grep: /Users/armenzg/.zshrc: No such file or directory
OK
--> Install volta
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10930  100 10930    0     0  29958      0 --:--:-- --:--:-- --:--:-- 30110
  Installing latest version of Volta (1.1.1)
    Checking for existing Volta installation
    Fetching archive for macOS, version 1.1.1
######################################################################## 100.0%
    Creating directory layout
  Extracting Volta binaries and launchers
    Finished installation. Updating user profile settings.
OK
--> Bootstrapping env: /Users/armenzg/code/sentry
--> Installing Yarn packages (for development)
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @monaco-editor/react@4.4.5" has unmet peer dependency "monaco-editor@>= 0.25.0 < 1".
warning "@monaco-editor/react > @monaco-editor/loader@1.3.2" has unmet peer dependency "monaco-editor@>= 0.21.0 < 1".
warning " > react-autosize-textarea@7.1.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > react-autosize-textarea@7.1.0" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > react-date-range@1.4.0" has unmet peer dependency "date-fns@2.0.0-alpha.7 || >=2.0.0".
warning " > react-lazyload@2.6.5" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > react-lazyload@2.6.5" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > react-router@3.2.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0-rc".
warning " > react-virtualized@9.22.3" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha".
warning " > react-virtualized@9.22.3" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
warning " > reflux@0.4.1" has incorrect peer dependency "react@>=0.13.0 <16".
warning " > @sentry/jest-environment@4.0.0" has incorrect peer dependency "@sentry/profiling-node@^0.2.2".
warning " > @testing-library/user-event@14.4.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "eslint-config-sentry-app > eslint-config-sentry-react > eslint-plugin-jest-dom@5.0.1" has unmet peer dependency "@testing-library/dom@^8.0.0 || ^9.0.0".
warning "eslint-config-sentry-app > eslint-config-sentry-react > eslint-plugin-typescript-sort-keys@2.3.0" has incorrect peer dependency "@typescript-eslint/parser@^1 || ^2 || ^3 || ^4 || ^5".
warning " > postcss-jsx@0.36.4" has unmet peer dependency "postcss@>=5.0.0".
warning " > postcss-syntax@0.36.2" has unmet peer dependency "postcss@>=5.0.0".
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
Done in 27.55s.
yarn check v1.22.5
success Folder in sync.
Done in 1.04s.
Looking in indexes: https://pypi.devinfra.sentry.io/simple
Collecting pip
  Downloading https://pypi.devinfra.sentry.io/wheels/pip-22.1.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 35.5 MB/s eta 0:00:00
Requirement already satisfied: setuptools in ./.venv/lib/python3.8/site-packages (56.0.0)
Collecting wheel
  Downloading https://pypi.devinfra.sentry.io/wheels/wheel-0.38.4-py3-none-any.whl (36 kB)
Installing collected packages: wheel, pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Successfully installed pip-22.1.2 wheel-0.38.4
--> Installing Sentry (for development)
Looking in indexes: https://pypi.devinfra.sentry.io/simple
Obtaining file:///Users/armenzg/code/sentry
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting six==1.16.0
  Downloading https://pypi.devinfra.sentry.io/wheels/six-1.16.0-py2.py3-none-any.whl (11 kB)
...
  Running setup.py develop for sentry
Successfully installed aiohttp-3.8.5 aiosignal-1.3.1 amqp-2.6.1 asgiref-3.7.2 async-generator-1.10 async-timeout-4.0.2 attrs-19.2.0 avalara-20.9.0 beautifulsoup4-4.7.1 billiard-3.6.4.0 black-22.10.0 boto3-1.22.12 botocore-1.25.12 brotli-1.0.9 build-0.8.0 cachetools-5.3.0 celery-4.4.7 certifi-2023.7.22 cffi-1.15.1 cfgv-3.3.1 charset-normalizer-3.0.1 click-8.0.4 confluent-kafka-2.1.1 covdefaults-2.3.0 coverage-6.3.3 croniter-1.3.10 cryptography-39.0.1 cssselect-1.0.3 cssutils-2.4.0 datadog-0.29.3 decorator-5.1.1 dictpath-0.1.3 distlib-0.3.4 django-3.2.20 django-crispy-forms-1.14.0 django-csp-3.7 django-pg-zero-downtime-migrations-0.13 django-stubs-4.2.3 django-stubs-ext-4.2.2 djangorestframework-3.14.0 djangorestframework-stubs-3.14.0 docker-3.7.0 docker-pycreds-0.4.0 drf-spectacular-0.26.3 email-reply-parser-0.5.12 exceptiongroup-1.0.0rc9 execnet-1.9.0 fastjsonschema-2.16.2 fido2-0.9.2 filelock-3.7.0 flake8-6.0.0 flake8-bugbear-22.10.27 freezegun-1.2.2 frozenlist-1.3.3 google-api-core-2.10.1 google-auth-2.16.0 google-cloud-bigtable-2.11.3 google-cloud-core-2.3.2 google-cloud-functions-1.8.1 google-cloud-pubsub-2.13.6 google-cloud-spanner-3.20.0 google-cloud-storage-2.5.0 google-crc32c-1.3.0 google-resumable-media-2.3.3 googleapis-common-protos-1.56.4 grpc-google-iam-v1-0.12.4 grpcio-1.56.0 grpcio-status-1.56.0 h11-0.13.0 hiredis-0.3.1 honcho-1.1.0 identify-2.5.24 idna-2.10 inflection-0.5.1 iniconfig-1.1.1 isodate-0.6.1 isort-5.10.1 jmespath-0.10.0 jsonschema-3.2.0 kombu-4.6.11 lazy-object-proxy-1.7.1 lxml-4.9.1 lxml-stubs-0.4.0 markupsafe-2.1.2 maxminddb-2.3.0 mccabe-0.7.0 milksnake-0.1.5 mistune-2.0.4 mmh3-4.0.0 more-itertools-8.13.0 msgpack-1.0.4 msgpack-types-0.2.0 multidict-6.0.4 mypy-1.4.1 mypy-extensions-1.0.0 nodeenv-1.6.0 oauthlib-3.1.0 openai-0.27.0 openapi-core-0.14.2 openapi-schema-validator-0.2.3 openapi-spec-validator-0.4.0 outcome-1.2.0 packaging-21.3 parse-1.19.0 parsimonious-0.8.0 pathspec-0.9.0 pep517-0.12.0 petname-2.6 phabricator-0.7.0 phonenumberslite-8.12.55 pillow-9.3.0 pip-tools-6.7.0 planout-0.6.0 platformdirs-2.5.2 pluggy-0.13.1 pre-commit-3.3.2 progressbar2-3.41.0 proto-plus-1.22.1 protobuf-4.21.6 psycopg2-binary-2.8.6 pyasn1-0.4.5 pyasn1-modules-0.2.4 pycodestyle-2.10.0 pycountry-17.5.14 pycparser-2.21 pydantic-1.10.9 pyflakes-3.0.1 pyjwt-2.4.0 pyopenssl-23.0.0 pyparsing-3.0.9 pyrsistent-0.18.1 pysocks-1.7.1 pytest-7.2.1 pytest-cov-4.0.0 pytest-django-4.4.0 pytest-fail-slow-0.3.0 pytest-rerunfailures-11.0 pytest-sentry-0.1.11 pytest-xdist-3.0.2 python-dateutil-2.8.1 python-memcached-1.59 python-rapidjson-1.8 python-u2flib-server-5.0.0 python-utils-3.3.3 python3-saml-1.15.0 pytz-2018.9 pyupgrade-3.2.3 pyuwsgi-2.0.20 pyvat-1.3.15 pyyaml-5.4 rb-1.10.0 redis-3.4.1 redis-py-cluster-2.1.0 reportlab-3.6.1 requests-2.31.0 requests-oauthlib-1.2.0 responses-0.23.1 rfc3339-validator-0.1.2 rfc3986-validator-0.1.1 rsa-4.8 s3transfer-0.5.2 selenium-4.3.0 sentry-23.8.0.dev0 sentry-arroyo-2.14.1 sentry-cli-2.16.0 sentry-kafka-schemas-0.1.22 sentry-redis-tools-0.1.7 sentry-relay-0.8.29 sentry-sdk-1.28.1 simplejson-3.17.6 six-1.16.0 sniffio-1.2.0 snuba-sdk-1.0.5 sortedcontainers-2.4.0 soupsieve-2.3.2.post1 sqlparse-0.4.4 statsd-3.3.0 stripe-2.61.0 structlog-22.1.0 symbolic-12.2.0 tokenize-rt-5.0.0 tomli-2.0.1 toronado-0.1.0 tqdm-4.64.1 trio-0.21.0 trio-websocket-0.9.2 types-beautifulsoup4-4.11.6 types-cachetools-5.3.0.5 types-croniter-1.3.2.9 types-jsonschema-4.16.1 types-oauthlib-3.2.0.8 types-parsimonious-0.10.0.8 types-pillow-9.5.0.4 types-protobuf-4.23.0.1 types-psycopg2-2.9.21 types-python-dateutil-2.8.19 types-pytz-2022.1.2 types-pyyaml-6.0.11 types-redis-4.3.13 types-requests-2.28.8 types-setuptools-65.3.0 types-simplejson-3.17.7.2 types-urllib3-1.26.22 typing-extensions-4.5.0 ua-parser-0.10.0 unidiff-0.7.4 uritemplate-4.1.1 urllib3-1.26.11 vine-1.3.0 virtualenv-20.14.1 websocket-client-1.3.2 werkzeug-2.2.3 wrapt-1.14.1 wsproto-1.1.0 xmlsec-1.3.12 yarl-1.8.2 zstandard-0.18.0

[notice] A new release of pip available: 22.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
--> Installing git hooks
/Users/armenzg/code/sentry
Running in migration mode with existing hooks at .git/hooks/pre-commit.legacy
Use -f to use only pre-commit.
pre-commit installed at .git/hooks/pre-commit
[INFO] Initializing environment for local:packaging==21.3.
[INFO] Initializing environment for https://github.com/python-jsonschema/check-jsonschema.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/python-jsonschema/check-jsonschema.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...

Attempting to start colima...
Error: unknown flag: --vm-type
Usage:
  colima start [profile] [flags]

Examples:
  colima start
  colima start --edit
  colima start --runtime containerd
  colima start --kubernetes
  colima start --runtime containerd --kubernetes
  colima start --cpu 4 --memory 8 --disk 100
  colima start --arch aarch64
  colima start --dns 1.1.1.1 --dns 8.8.8.8
  colima start --dns-host example.com=1.2.3.4
  colima start --kubernetes --kubernetes-disable=coredns,servicelb,traefik,local-storage,metrics-server

Flags:
      --activate                    set as active Docker/Kubernetes context on startup (default true)
  -a, --arch string                 architecture (aarch64, x86_64) (default "aarch64")
  -c, --cpu int                     number of CPUs (default 2)
      --cpu-type string             the CPU type, options can be checked with 'qemu-system-aarch64 -cpu help'
  -d, --disk int                    disk size in GiB (default 60)
  -n, --dns ipSlice                 DNS resolvers for the VM (default [])
      --dns-host strings            custom DNS names to provide to resolver
  -e, --edit                        edit the configuration file before starting
      --editor string               editor to use for edit e.g. vim, nano, code (default "$EDITOR" env var)
      --env stringToString          environment variables for the VM (default [])
  -h, --help                        help for start
      --k3s-arg strings             additional args to pass to k3s (default [--disable=traefik])
  -k, --kubernetes                  start with Kubernetes
      --kubernetes-version string   must match a k3s version https://github.com/k3s-io/k3s/releases (default "v1.27.1+k3s1")
  -l, --layer                       enable Ubuntu container layer
  -m, --memory int                  memory in GiB (default 2)
  -V, --mount strings               directories to mount, suffix ':w' for writable
      --mount-inotify               propagate inotify file events to the VM
      --mount-type string           volume driver for the mount (sshfs, 9p, virtiofs) (default "sshfs")
      --network-address             assign reachable IP address to the VM
      --network-driver string       network driver to use (gvproxy, slirp) (default "gvproxy")
  -r, --runtime string              container runtime (docker, containerd) (default "docker")
  -s, --ssh-agent                   forward SSH agent to the VM
      --ssh-config                  generate SSH config in ~/.ssh/config (default true)

Global Flags:
  -p, --profile string   profile name, for multiple instances (default "default")
  -v, --verbose          enable verbose log
      --very-verbose     enable more verbose log

time="2023-08-14T13:23:29Z" level=fatal msg="unknown flag: --vm-type"
Traceback (most recent call last):
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/armenzg/code/sentry/src/sentry/runner/commands/devservices.py", line 43, in get_docker_client
    client.ping()
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/docker/client.py", line 187, in ping
    return self.api.ping(*args, **kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/docker/api/daemon.py", line 166, in ping
    return self._result(self._get(self._url('/_ping'))) == 'OK'
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/docker/api/client.py", line 225, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/armenzg/code/sentry/.venv/bin/sentry", line 33, in <module>
    sys.exit(load_entry_point('sentry', 'console_scripts', 'sentry')())
  File "/Users/armenzg/code/sentry/src/sentry/runner/__init__.py", line 193, in main
    func(**kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/armenzg/code/sentry/src/sentry/runner/commands/devservices.py", line 260, in up
    with get_docker_client() as docker_client:
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/armenzg/code/sentry/src/sentry/runner/commands/devservices.py", line 48, in get_docker_client
    subprocess.check_call(
  File "/Users/armenzg/.pyenv/versions/3.8.16/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('python3', '-uS', '/Users/armenzg/code/sentry/src/sentry/runner/commands/../../../../scripts/start-colima.py')' returned non-zero exit status 1.
make: *** [bootstrap] Error 1
armenzg@MacBook-Air ~ %  

```

**Comment by joshuarli** [comment]
Big Sur? That's way outdated. I'm guessing brew installed an older version of colima because of that. Update your Mac to latest and try again.

**Comment by armenzg** [comment]
> Big Sur? That's way outdated. I'm guessing brew installed an older version of colima because of that. Update your Mac to latest and try again.
> 
> I should add a MacOS minimum supported version check.

Hi @joshuarli 
It was a brand new laptop that had not yet been updated.

I guess I should update everything brew installed.

**Comment by joshuarli** [comment]
ref: https://github.com/getsentry/bootstrap-sentry/pull/51
